[package]
name = "phishing_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
log = "0.4.22"
env_logger = "0.11.5"
url = "2.5.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
lazy_static = "1.5.0"
rayon = "1.10.0"  # For parallelism
tracing = "0.1.40"  # Advanced logging

[build-dependencies]
cc = "1.1.28"

[dev-dependencies]
tempfile = "3.13.0"